name: Deployment pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches: [main]
    types: [opened, synchronized]

jobs:
  deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: 
          node-version: '12.x'
      - name: npm install server
        run: npm install
      - name: npm install client
        run: cd client && npm install
      - name: lint
        run: npm run lint
      - name: build ui
        run: npm run build:ui
      - name: test
        run: cd client && npm run test
      - name: e2e test
        uses: cypress-io/github-action@v2
        with:
          command: npm run e2e:test
          start: npm run dev
          wait-on: http://localhost:${{secrets.PORT}}
        env:
          PORT: ${{secrets.PORT}}
          MONGODB_URI: ${{secrets.MONGODB_URI}}
      - uses: AkhileshNS/heroku-deploy@v3.12.12
        if: ${{github.event_name == 'push' && !contains(github.event.commits.*.message, '#skip')}}
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "hidden-oasis-09339"
          heroku_email: "gabrielhgiraldo@gmail.com"
          healthcheck: 'https://hidden-oasis-09339.herokuapp.com/health'
          checkstring: 'ok'
          rollbackonhealthcheckfailed: true