name: Deployment pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches: [main]
    types: [opened, synchronized]

jobs:
  deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: 
          node-version: '12.x'
      - name: npm install server
        run: npm install
      - name: npm install client
        run: cd client && npm install
      - name: lint
        run: npm run lint
      - name: build ui
        run: npm run build:ui
      - uses: AkhileshNS/heroku-deploy@v3.12.12